version: '3'
services:
  app1:
    build: ./app1
    container_name: app1
    ports:
    - "81:80"
  app2:
    build: ./app2
    container_name: app2
    ports:
    - "82:80"
  nginx:
    build: ./nginx
    ports:
    - "80:80"
    links:
        - app1
        - app2
