version: '3'
services:
  app1:
    build: ./app1
    container_name: app1
    ports:
    - "81:443"
  app2:
    build: ./app2
    container_name: app2
    ports:
    - "82:443"
  nginx:
    build: ./nginx
    ports:
#    - "80:80"
    - "443:443"
    links:
        - app1
        - app2
